server:
  port: 9000
spring:
  application:
    name: ribbon-invoker
#ribbon-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.haiyu.MyRule
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/